# Generated by Django 5.2.8 on 2025-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
